name: stats

on:
  schedule:
    - cron: "0 6 * * SUN"
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Push update
        shell: bash
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'Pierre Manchon'
            git config user.email 'pierre.manchon@pm.me'
            git add *.md
            git commit -m "Update README.md"
            git push
          fi
